// Commands module
// 定义所有Tauri命令

pub mod ai_commands;
pub mod app_launcher_commands;
pub mod autostart_commands;
pub mod clipboard_commands;
pub mod context_commands;
pub mod db_repair_commands;
pub mod milestone_commands;
pub mod notification_commands;
pub mod pomodoro_commands;
pub mod prediction_commands;
pub mod prompt_commands;
pub mod prompt_db_commands;
pub mod report_commands;
pub mod scheduler_commands;
pub mod screenshot_commands;
pub mod settings_commands;
pub mod shortcut_commands;
pub mod sql_ai_commands;
pub mod sql_commands;
pub mod sql_template_commands;
pub mod tips_commands;
pub mod statistics_commands;
pub mod system_commands;
pub mod tag_commands;
pub mod task_commands;
pub mod timeline_commands;
pub mod vlm_commands;
pub mod weekly_plan_commands;
pub mod window_commands;
pub mod work_log_commands;
pub mod tool_commands;
pub mod file_search_commands;
pub mod file_index_commands;
